-- AgriSense Supabase Seed Script
-- Populates auth.users and public tables with default pilot data.

-- 1. SEED DEFAULT USERS INTO auth.users
-- Admin: admin@agrisense.io / admin123
-- Farmer: farmer@agrisense.io / farmer123
-- Agronomist: agronomist@agrisense.io / agro123
-- Technician: technician@agrisense.io / tech123
-- Uses standard pgcrypto crypt function to encrypt passwords with standard blowfish salt (bcrypt-compatible).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO auth.users (
    id, 
    instance_id, 
    email, 
    encrypted_password, 
    email_confirmed_at, 
    raw_app_meta_data, 
    raw_user_meta_data, 
    created_at, 
    updated_at, 
    role, 
    aud, 
    is_super_admin
)
VALUES 
(
    '00000000-0000-0000-0000-000000000001', 
    '00000000-0000-0000-0000-000000000000', 
    'admin@agrisense.io', 
    extensions.crypt('admin123', extensions.gen_salt('bf')), 
    now(), 
    '{"provider":"email","providers":["email"]}', 
    '{"role":"Administrator","full_name":"Admin Name","username":"admin"}', 
    now(), 
    now(), 
    'authenticated', 
    'authenticated', 
    false
),
(
    '00000000-0000-0000-0000-000000000002', 
    '00000000-0000-0000-0000-000000000000', 
    'farmer@agrisense.io', 
    extensions.crypt('farmer123', extensions.gen_salt('bf')), 
    now(), 
    '{"provider":"email","providers":["email"]}', 
    '{"role":"Farmer","full_name":"Moses Farmer","username":"farmer1","farm_name":"Moses Farm","farm_location":"{\\"district\\":\\"Mbarara\\",\\"village\\":\\"Ruti\\",\\"gps\\":\\"-0.6074, 30.6548\\"}"}', 
    now(), 
    now(), 
    'authenticated', 
    'authenticated', 
    false
),
(
    '00000000-0000-0000-0000-000000000003', 
    '00000000-0000-0000-0000-000000000000', 
    'agronomist@agrisense.io', 
    extensions.crypt('agro123', extensions.gen_salt('bf')), 
    now(), 
    '{"provider":"email","providers":["email"]}', 
    '{"role":"Agronomist","full_name":"Dr. Sarah Agronomist","username":"agronomist1"}', 
    now(), 
    now(), 
    'authenticated', 
    'authenticated', 
    false
),
(
    '00000000-0000-0000-0000-000000000004', 
    '00000000-0000-0000-0000-000000000000', 
    'technician@agrisense.io', 
    extensions.crypt('tech123', extensions.gen_salt('bf')), 
    now(), 
    '{"provider":"email","providers":["email"]}', 
    '{"role":"Technician","full_name":"Dan Technician","username":"technician1"}', 
    now(), 
    now(), 
    'authenticated', 
    'authenticated', 
    false
)
ON CONFLICT (id) DO NOTHING;

-- 2. OPERATIONAL TELEMETRY SEEDS BLOCK
DO $$
DECLARE
    v_farm_id UUID;
    v_greenhouse_id UUID;
    v_garden_id UUID;
    v_device_id UUID;
    v_pump_id UUID;
    v_sensor_a_id UUID;
    v_sensor_b_id UUID;
    v_sensor_c_id UUID;
    v_sensor_d_id UUID;
    v_solar_id UUID;
BEGIN
    -- Retrieve the farm id generated by the user trigger for farmer1
    SELECT id INTO v_farm_id FROM public.farms WHERE owner_id = '00000000-0000-0000-0000-000000000002' LIMIT 1;
    
    -- Fallback in case of trigger failure/manual setup
    IF v_farm_id IS NULL THEN
        INSERT INTO public.farms (owner_id, farm_name, district, village, latitude, longitude, description)
        VALUES ('00000000-0000-0000-0000-000000000002', 'Mbarara Pilot Farm', 'Mbarara', 'Ruti', -0.6074, 30.6548, 'Interactive simulation farm site')
        RETURNING id INTO v_farm_id;
    END IF;

    -- Create Greenhouse
    INSERT INTO public.greenhouses (farm_id, name, location_details)
    VALUES (v_farm_id, 'Greenhouse Alpha', 'North cultivation quadrant')
    RETURNING id INTO v_greenhouse_id;

    -- Create Outdoor Garden
    INSERT INTO public.outdoor_gardens (farm_id, name, crop_type, area_sq_meters)
    VALUES (v_farm_id, 'Coffee Fields East', 'Coffee', 1200.0)
    RETURNING id INTO v_garden_id;

    -- Create Hardware Device Gateway
    INSERT INTO public.esp32_devices (farm_id, device_name, mac_address, firmware_version, status)
    VALUES (v_farm_id, 'Main Gateway Node', '24:0A:C4:B3:11:40', 'v1.4.2', 'active')
    RETURNING id INTO v_device_id;

    -- Create Pump
    INSERT INTO public.pumps (farm_id, name, status, flow_rate_lpm)
    VALUES (v_farm_id, 'Primary Water Pump', false, 60.0)
    RETURNING id INTO v_pump_id;

    -- Create Soil Moisture Sensors (Nodes A, B, C, D)
    INSERT INTO public.soil_moisture_sensors (greenhouse_id, garden_id, device_id, sensor_code, crop, depth_cm, min_moisture, max_moisture, current_moisture, current_temp, online, irrigating)
    VALUES (v_greenhouse_id, NULL, v_device_id, 'NODE-A', 'Tomato', 20, 35, 75, 42.5, 26.2, true, false)
    RETURNING id INTO v_sensor_a_id;

    INSERT INTO public.soil_moisture_sensors (greenhouse_id, garden_id, device_id, sensor_code, crop, depth_cm, min_moisture, max_moisture, current_moisture, current_temp, online, irrigating)
    VALUES (v_greenhouse_id, NULL, v_device_id, 'NODE-B', 'Sweet Pepper', 30, 40, 80, 28.1, 25.8, true, false)
    RETURNING id INTO v_sensor_b_id;

    INSERT INTO public.soil_moisture_sensors (greenhouse_id, garden_id, device_id, sensor_code, crop, depth_cm, min_moisture, max_moisture, current_moisture, current_temp, online, irrigating)
    VALUES (NULL, v_garden_id, v_device_id, 'NODE-C', 'Coffee', 40, 30, 70, 52.0, 23.4, true, false)
    RETURNING id INTO v_sensor_c_id;

    INSERT INTO public.soil_moisture_sensors (greenhouse_id, garden_id, device_id, sensor_code, crop, depth_cm, min_moisture, max_moisture, current_moisture, current_temp, online, irrigating)
    VALUES (NULL, v_garden_id, v_device_id, 'NODE-D', 'Maize', 10, 25, 65, 18.4, 28.7, false, false)
    RETURNING id INTO v_sensor_d_id;

    -- Create Valves
    INSERT INTO public.valves (pump_id, name, status, target_moisture_sensor_id)
    VALUES (v_pump_id, 'Valve Alpha-1 (Tomato)', false, v_sensor_a_id);

    INSERT INTO public.valves (pump_id, name, status, target_moisture_sensor_id)
    VALUES (v_pump_id, 'Valve Alpha-2 (Pepper)', false, v_sensor_b_id);

    INSERT INTO public.valves (pump_id, name, status, target_moisture_sensor_id)
    VALUES (v_pump_id, 'Valve East-1 (Coffee)', false, v_sensor_c_id);

    -- Create Weather Station
    INSERT INTO public.weather_stations (farm_id, name, model_info)
    VALUES (v_farm_id, 'Mbarara Weather Station', 'Davis Vantage Pro2');

    -- Create Battery Records
    SELECT id INTO v_solar_id FROM public.solar_system WHERE farm_id = v_farm_id LIMIT 1;
    IF v_solar_id IS NULL THEN
        INSERT INTO public.solar_system (farm_id, current_output_watts, status)
        VALUES (v_farm_id, 320.0, 'active')
        RETURNING id INTO v_solar_id;
    END IF;

    INSERT INTO public.batteries (solar_id, charge_percent, voltage, status)
    VALUES (v_solar_id, 86.5, 12.8, 'healthy');

    -- Insert moisture history log readings
    INSERT INTO public.moisture_readings (sensor_id, value, temp_value, timestamp)
    VALUES 
    (v_sensor_a_id, 41.2, 25.8, now() - interval '3 hours'),
    (v_sensor_a_id, 42.0, 26.0, now() - interval '2 hours'),
    (v_sensor_a_id, 42.5, 26.2, now() - interval '1 hour'),
    
    (v_sensor_b_id, 30.2, 25.5, now() - interval '3 hours'),
    (v_sensor_b_id, 29.1, 25.6, now() - interval '2 hours'),
    (v_sensor_b_id, 28.1, 25.8, now() - interval '1 hour'),
    
    (v_sensor_c_id, 51.5, 23.0, now() - interval '2 hours'),
    (v_sensor_c_id, 52.0, 23.4, now() - interval '1 hour');

    -- Insert AI recommendation records
    INSERT INTO public.ai_recommendations (farm_id, query, recommendation, created_by)
    VALUES (
        v_farm_id, 
        'Analyze overall soil health', 
        'Overall farm moisture average is adequate (40.8% VWC). However, Sweet Pepper (NODE-B) is currently at 28.1% VWC, which is below its 40% optimal threshold. Suggest triggering Valve Alpha-2 for a 15-minute operational irrigation interval.', 
        '00000000-0000-0000-0000-000000000003'
    );

    -- Insert Alerts
    INSERT INTO public.notifications (farm_id, user_id, type, message, read)
    VALUES 
    (v_farm_id, '00000000-0000-0000-0000-000000000002', 'warning', 'Sweet Pepper (NODE-B) moisture index below 40% trigger threshold.', false),
    (v_farm_id, '00000000-0000-0000-0000-000000000002', 'alert', 'Node D (Maize) sensor probe has gone offline. Check battery connection.', false);

END $$;
